name: Build

on:
  workflow_call:
    inputs:
      repository:
        description: Repository to clone and build
        type: string
        default: zed-industries/zed
      ref:
        description: Branch/tag/ref to build
        type: string
        required: true
  workflow_dispatch:
    inputs:
      repository:
        description: Repository to clone and build
        type: string
        default: zed-industries/zed
      ref:
        description: Branch/tag/ref to build
        type: string
        default: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout Zed
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: zed

      - name: Install dependencies
        run: |
          chmod +x zed/script/linux
          sudo ./zed/script/linux

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: opengl-${{ hashFiles('Cargo.lock') }}
          workspaces: "zed -> target"

      - name: Build release
        working-directory: zed
        env:
          ZED_UPDATE_EXPLANATION: "This is a custom build."
          RUSTFLAGS: "--cfg gles"
        run: cargo build --release

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: zed-linux-gles
          path: zed/target/release/zed
